# Generated by Django 3.2.9 on 2021-11-09 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211109_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 9, 15, 59, 55, 433813, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
