# Generated by Django 3.2.9 on 2021-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20211110_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='com_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
